# k8s/backend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: tareas-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tareas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sebastianveloza/backend-tareas:latest
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: mysql
