# k8s/frontend-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: tareas-app
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tareas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sebastianveloza/frontend-tareas:k8s-fix
          ports:
            - containerPort: 3000
